apiVersion: v1
kind: Secret
metadata:
  name: {{ include "timelapser.fullname" . }}-creds
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: {{.Values.buckets.accessKeyId}}
  AWS_SECRET_ACCESS_KEY: {{.Values.buckets.secretAccessKey}}
  {{- if .Values.telegram.botToken }}
  TELEGRAM_BOT_TOKEN: {{.Values.telegram.botToken}}
  {{- end -}}
  {{- if .Values.telegram.chatId }}
  TELEGRAM_CHAT_ID: {{.Values.telegram.chatId | quote}}
  {{- end -}}
